# Nom de l'application
spring.application.name=demo

# Configuration de la datasource en mémoire H2
spring.datasource.url=jdbc:h2:mem:demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Génération automatique du schéma JPA à chaque démarrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Désactiver le warning open-in-view
spring.jpa.open-in-view=false

# Console H2 accessible à http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration SpringDoc OpenAPI

springdoc.swagger-ui.path=/swagger-ui.html

# Configuration du serveur
server.port=${PORT:8080}

# Activer Swagger en production
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=false
